version: "3.8"

services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INIT_COMPLETE_FILE_PATH: ${MONGO_INIT_COMPLETE_FILE_PATH}
      APP_MONGO_DATABASE: ${APP_MONGO_DATABASE}
      APP_MONGO_USERNAME: ${APP_MONGO_USERNAME}
      APP_MONGO_PASSWORD: ${APP_MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: mongod --port ${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    networks:
      - app-tier
    restart: always
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/db:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", 'db.adminCommand("ping")', '--port', '${MONGO_PORT}']
      interval: 30s
      timeout: 10s
      retries: 1

networks:
  app-tier:
    driver: bridge